name: Scheduled Build

on:
  schedule:
    # UTC 15:00 ＝ 日本時間（JST）0:00
    - cron: '0 15 * * *'
  # 手動で実行ボタンを押せるようにする設定
  workflow_dispatch:

jobs:
  trigger-build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub Pages rebuild
        uses: actions/checkout@v4
